// export const airplane_comercial = {"company_name" : 
// {

//             "Airbus A220_100": {
//                 "length": 35.0,
//                 "capacity": 133,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "2016",
//                 "engine_manufacturer": "Pratt & Whitney",
//                 "engine_name": "PW1500G",
//                 "models_built": 108,
//                 "topspeed": 829,
//                 "number_engines": 2,
//                 "wingspan": 35.1,
//                 "width": 3.28,
//                 "flight_range": 6390,
//                 "engine_type": "High-bypass turbofan",
//                 "first_flight": "2013",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["Delta Air Lines", "airBaltic", "Air France", "Air Canada", "JetBlue", "Korean Air", "Air Manas"],
//                 "highest_altitude": 41000,
//                 "aircraft_image": "https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSa_k4SDs-LxHg-2RRr9j5xZ-P0DfGX8UnBbIxH-aFVDIWB0hypjfl7IxnuX4x0"
//             },
//             "Airbus A220_300": {
//                 "length": 38.7,
//                 "capacity": 160,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "2016",
//                 "engine_manufacturer": "Pratt & Whitney",
//                 "engine_name": "PW1500G",
//                 "models_built": 602,
//                 "topspeed": 829,
//                 "number_engines": 2,
//                 "wingspan": 35.1,
//                 "width": 3.28,
//                 "flight_range": 6297,
//                 "engine_type": "High-bypass turbofan",
//                 "first_flight": "2015",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["Delta Air Lines", "airBaltic", "Air France", "Air Canada"],
//                 "highest_altitude": 41000,
//                 "aircraft_image": "https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTdz1QN0s9UBWKiLwkKgCi_FOqX7PrxHqm5rK2AHs6tUC121Eo369BpBJJA6K_2"
//             },
//         "Airbus A300": {
//             "engine_manufacturer": "General Electric",
//             "engine_name": "General Electric CF6",
//             "models_built": 228,
//             "topspeed": 897,
//             "number_engines": 2,
//             "wingspan": 44.84,
//             "width": 5.64,
//             "length": 54.08,
//             "capacity": 345,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "1974",
//             "flight_range": 5375,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "1972",
//             "type": "Medium to long range",
//             "airline_companies_used": ["FedEx Express", "UPS Airlines", "European Air Transport Leipzig", "Mahan Air", "MNG Airlines", "Solinair", "Iran Air", "Iran Airtour", "Qeshm Air"],
//             "highest_altitude": 35000,
//             "aircraft_image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQPyG3KTy4BZYvvJwuQcgDqtcjjHIE8RKTMfqU02rO3Hm6SM_E5IG2BWbGvkGr6"
//         },
//         "Airbus A300B1": {
//             "length": 53.62,
//             "capacity": 250,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "1974",
//             "engine_manufacturer": "General Electric",
//             "engine_name": "CF6-50",
//             "models_built": 561,
//             "topspeed": 871,
//             "number_engines": 2,
//             "wingspan": 44.84,
//             "width": 5.28,
//             "flight_range": 3426,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "1972",
//             "type": "Medium to long range",
//             "airline_companies_used": ["Air France", "Lufthansa", "Iberia", "Olympic Airways"],
//             "highest_altitude": 35000,
//             "aircraft_image": "https://th.bing.com/th/id/R.ee60226100525dc7880ff674f87f63a5?rik=F56JtxFWNnbdTw&riu=http%3a%2f%2fimgproc.airliners.net%2fphotos%2fairliners%2f5%2f4%2f0%2f0912045.jpg%3fv%3dv40&ehk=QOh4f1QGc8xwvDLhiam0Qtnp0Emb1EoJAW41YdTs2%2f8%3d&risl=&pid=ImgRaw&r=0"
//         },
//         "Airbus A310": {
//             "engine_manufacturer": "General Electric",
//             "engine_name": "General Electric CF6",
//             "models_built": 187,
//             "topspeed": 897,
//             "number_engines": 2,
//             "wingspan": 43.9,
//             "width": 5.28,
//             "length": 46.66,
//             "capacity": 279,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "1983",
//             "flight_range": 6700,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "1982",
//             "type": "Medium to long range",
//             "airline_companies_used": ["Air India", "Aeroflot", "Air Calin", "Cyprus Airways", "Czech Airlines", "Kuwait Airways", "Air Afrique", "Pakistan International Airlines", "SATA"],
//             "highest_altitude": 41100,
//             "aircraft_image": "https://th.bing.com/th/id/R.d1d412947f6f45fbac2c202404de5755?rik=qpKR15%2bI2WJ7eQ&pid=ImgRaw&r=0"
//         },
//         "Airbus A318": {
//             "engine_manufacturer": "General Electric",
//             "engine_name": "CFM International CFM56",
//             "models_built": 80,
//             "topspeed": 900,
//             "number_engines": 2,
//             "wingspan": 34.1,
//             "width": 3.95,
//             "length": 31.45,
//             "capacity": 132,
//             "cockpit_crew": 2,
//             "body_type": "narrow-body",
//             "num_decks": 1,
//             "YOEIS": "2003",
//             "flight_range": 3100,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "2002",
//             "type": "Short to medium range",
//             "airline_companies_used": ["Air France", "TAROM"],
//             "highest_altitude": 39000,
//             "aircraft_image": "https://th.bing.com/th/id/OIP.Yku1-u9Bp_GgU3i2MN9srwHaFm?rs=1&pid=ImgDetMain"
//         },
//         "Airbus A319": {
//             "engine_manufacturer": "CFM International",
//             "engine_name": "CFM International CFM56",
//             "models_built": 1500,
//             "topspeed": 900,
//             "number_engines": 2,
//             "wingspan": 34.1,
//             "width": 3.7,
//             "length": 33.84,
//             "capacity": 156,
//             "cockpit_crew": 2,
//             "body_type": "narrow-body",
//             "num_decks": 1,
//             "YOEIS": "1996",
//             "flight_range": 3700,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "1995",
//             "type": "Short to medium range",
//             "airline_companies_used": ["easyJet", "American Airlines", "United Airlines", "Delta Air Lines", "Tibet Airlines", "Hunan Airlines", "Chengdu Airlines", "Shenzhen Airlines", "Myanmar Airways"],
//             "highest_altitude": 41100,
//             "aircraft_image": "https://th.bing.com/th/id/OIP.Md2vrQQ37QJleMRjRI4KhQHaE9?rs=1&pid=ImgDetMain"
//         },
//         "Airbus A320": {
//             "engine_manufacturer": "CFM International",
//             "engine_name": "CFM International CFM56",
//             "models_built": 17757,
//             "topspeed": 903,
//             "number_engines": 2,
//             "wingspan": 35.8,
//             "width": 3.7,
//             "length": 37.57,
//             "capacity": 186,
//             "cockpit_crew": 2,
//             "body_type": "narrow-body",
//             "num_decks": 1,
//             "YOEIS": "1988",
//             "flight_range": 6100,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "1987",
//             "type": "Short to medium range",
//             "airline_companies_used": ["Delta Air Lines", "Lufthansa", "Air France", "British Airways", "Singapore Airlines", "Qatar Airways", "AirAsia", "Thai AirAsia", "Thai Vietjet", "China Southern Airlines"],
//             "highest_altitude": 39100,
//             "aircraft_image": "https://upload.wikimedia.org/wikipedia/commons/3/30/Airbus_A320-200_Airbus_Industries_(AIB)_%22House_colors%22_F-WWBA_-_MSN_001_(10276181983).jpg"
//         },
       
        
//             "Airbus A320 neo": {
//                 "length": 37.57,
//                 "capacity": 194,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "2016",
//                 "engine_manufacturer": "CFM International",
//                 "engine_name": "LEAP-1A",
//                 "models_built": 602,
//                 "topspeed": 829,
//                 "number_engines": 2,
//                 "wingspan": 35.8,
//                 "width": 3.95,
//                 "flight_range": 6300,
//                 "engine_type": "High-bypass turbofan",
//                 "first_flight": "2014",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["IndiGo", "Wizz Air", "China Southern Airlines", "Frontier Airlines"],
//                 "highest_altitude": 41000,
//                 "aircraft_image": "https://economyclassandbeyond.boardingarea.com/wp-content/uploads/2018/09/521425.jpg"
//             },
//             "Airbus A321": {
//                 "length": 44.51,
//                 "capacity": 236,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1994",
//                 "engine_manufacturer": "IAE",
//                 "engine_name": "V2500",
//                 "models_built": 3145,
//                 "topspeed": 828,
//                 "number_engines": 2,
//                 "wingspan": 34.1,
//                 "width": 3.95,
//                 "flight_range": 5600,
//                 "engine_type": "High-bypass turbofan",
//                 "first_flight": "1993",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["American Airlines", "Delta Air Lines", "China Southern Airlines", "Wizz Air"],
//                 "highest_altitude": 41000,
//                 "aircraft_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/72/D-AIAF_(19552328044).jpg/1200px-D-AIAF_(19552328044).jpg"
//             },
//             "Airbus A321 neo": {
//                 "length": 44.51,
//                 "capacity": 244,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "2017",
//                 "engine_manufacturer": "CFM International",
//                 "engine_name": "LEAP-1A",
//                 "models_built": 1339,
//                 "topspeed": 828,
//                 "number_engines": 2,
//                 "wingspan": 35.8,
//                 "width": 3.95,
//                 "flight_range": 7400,
//                 "engine_type": "High-bypass turbofan",
//                 "first_flight": "2016",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["Wizz Air", "IndiGo", "American Airlines", "China Southern Airlines"],
//                 "highest_altitude": 41000,
//                 "aircraft_image": "https://cdn.luxuo.com/2015/01/A321neo.jpg"
//             },
//             "Airbus A321XLR": {
//                 "length": 44.51,
//                 "capacity": 220,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "2024",
//                 "engine_manufacturer": "CFM International",
//                 "engine_name": "LEAP-1A",
//                 "models_built": 550,
//                 "topspeed": 828,
//                 "number_engines": 2,
//                 "wingspan": 35.8,
//                 "width": 3.95,
//                 "flight_range": 8700,
//                 "engine_type": "High-bypass turbofan",
//                 "first_flight": "2023",
//                 "type": "Long range",
//                 "airline_companies_used": ["Aer Lingus", "Air Canada", "American Airlines", "Iberia", "Qantas", "United Airlines", "Air Arabia", "AirAsia X", "flynas", "IndiGo", "JetBlue"],
//                 "highest_altitude": 41000,
//                 "aircraft_image": "https://th.bing.com/th/id/R.a083e324498dd3d7a51ceefe758ae8c0?rik=GqDzPQ1gp%2bjC7g&riu=http%3a%2f%2faustralianaviation.com.au%2fwp-content%2fuploads%2f2018%2f10%2fA321LR-in-flight-004_1170.jpg&ehk=tY4Jkr6sChs2%2f8NfBcf5HfAjc%2fzc8E5xf2pOJLOw65k%3d&risl=&pid=ImgRaw&r=0"
//         },
//         "Airbus A330-200": {
//             "length": 58.82,
//             "capacity": 260,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "1998",
//             "engine_manufacturer": "General Electric, Pratt & Whitney, Rolls-Royce",
//             "engine_name": "CF6, PW4000, Trent 700",
//             "models_built": 660,
//             "topspeed": 880,
//             "number_engines": 2,
//             "wingspan": 60.3,
//             "width": 5.64,
//             "flight_range": 13400,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "1997",
//             "type": "Long range",
//             "airline_companies_used": ["Delta Air Lines", "Turkish Airlines", "China Eastern Airlines", "Cathay Pacific"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://images.aircharterservice.com/global/aircraft-guide/group-charter/airbus-a330-200-1.jpg"
//         },
//         "Airbus A330-200F": {
//             "length": 58.82,
//             "capacity": 0,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "2010",
//             "engine_manufacturer": "General Electric, Pratt & Whitney, Rolls-Royce",
//             "engine_name": "CF6, PW4000, Trent 700",
//             "models_built": 38,
//             "topspeed": 871,
//             "number_engines": 2,
//             "wingspan": 60.3,
//             "width": 5.64,
//             "flight_range": 7400,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "2009",
//             "type": "Freighter",
//             "airline_companies_used": ["Etihad Cargo", "Turkish Cargo", "Qatar Airways Cargo", "MASkargo"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://th.bing.com/th/id/R.1dd70d54f4c82d51983bcc3c3bf52c45?rik=p5r%2f6ST8CB4b8w&riu=http%3a%2f%2fwww.aviaexpo.com%2fwp-content%2fuploads%2f2016%2f11%2fA330-200F-900x636.jpg&ehk=T6Q7xmHhNM0eVkIvkR2IKsNgQOBFFXG6eiLZbegEPsc%3d&risl=&pid=ImgRaw&r=0"
//         },
//         "Airbus A330-300": {
//             "length": 63.66,
//             "capacity": 290,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "1994",
//             "engine_manufacturer": "General Electric, Pratt & Whitney, Rolls-Royce",
//             "engine_name": "CF6, PW4000, Trent 700",
//             "models_built": 816,
//             "topspeed": 871,
//             "number_engines": 2,
//             "wingspan": 60.3,
//             "width": 5.64,
//             "flight_range": 11750,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "1992",
//             "type": "Long range",
//             "airline_companies_used": ["Delta Air Lines", "Turkish Airlines", "China Eastern Airlines", "Cathay Pacific"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://th.bing.com/th/id/R.caf35340554dc810194eb30ee8884d70?rik=XQHErStDch5CeA&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2f6%2f6c%2fQantas_Airbus_A330-300%2c_SIN.jpg&ehk=kWrDO%2f5NUJxsgNFPGqaubQ0%2bR98OhIKfSvTn83Gh7kY%3d&risl=&pid=ImgRaw&r=0"
//         },
//         "Airbus A330-800 neo": {
//             "length": 58.82,
//             "capacity": 260,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "2020",
//             "engine_manufacturer": "Rolls-Royce",
//             "engine_name": "Trent 7000",
//             "models_built": 15,
//             "topspeed": 871,
//             "number_engines": 2,
//             "wingspan": 64,
//             "width": 5.64,
//             "flight_range": 15100,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "2018",
//             "type": "Long range",
//             "airline_companies_used": ["Kuwait Airways", "Uganda Airlines"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://th.bing.com/th/id/R.771d608b116092df755487f5ecd9cedd?rik=QE8rkA4LUBNUxg&riu=http%3a%2f%2fwww.airportspotting.com%2fwp-content%2fuploads%2f2018%2f11%2fA330-800-MSN1888-first-flight-air-to-air-035.jpg&ehk=lQXbGiEGTU04wIrtxsDSltSJ2CmerkUTajDYa4oHirg%3d&risl=&pid=ImgRaw&r=0"
//         },
//         "Airbus A330-900 neo": {
//             "length": 63.66,
//             "capacity": 300,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "2018",
//             "engine_manufacturer": "Rolls-Royce",
//             "engine_name": "Trent 7000",
//             "models_built": 131,
//             "topspeed": 871,
//             "number_engines": 2,
//             "wingspan": 64,
//             "width": 5.64,
//             "flight_range": 13330,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "2017",
//             "type": "Long range",
//             "airline_companies_used": ["Delta Air Lines", "TAP Air Portugal", "AirAsia X", "Lion Air"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://media.wired.com/photos/59e8ec9d936a586d250ea90d/191:100/pass/A330neo-fHP.jpg"
//         },            
//         "Airbus A340-200": {
//             "length": 59.39,
//             "capacity": 250,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "1993",
//             "engine_manufacturer": "CFM International",
//             "engine_name": "CFM56-5C3/G4",
//             "models_built": 28,
//             "topspeed": 915,
//             "number_engines": 4,
//             "wingspan": 60.30,
//             "width": 5.64,
//             "flight_range": 12400,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "1992",
//             "type": "Long range",
//             "airline_companies_used": ["Lufthansa", "Air France"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Airbus_A340-311%2C_Lufthansa_AN1936774.jpg"
//         },
//         "Airbus A340-300": {
//             "length": 63.69,
//             "capacity": 290,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "1993",
//             "engine_manufacturer": "CFM International",
//             "engine_name": "CFM56-5C4",
//             "models_built": 218,
//             "topspeed": 915,
//             "number_engines": 4,
//             "wingspan": 60.30,
//             "width": 5.64,
//             "flight_range": 13500,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "1991",
//             "type": "Long range",
//             "airline_companies_used": ["Lufthansa", "Air France", "Iberia", "South African Airways"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://th.bing.com/th/id/R.e637663147e81f74eaf433feff34fef7?rik=4XJAw97RUN5vBw&pid=ImgRaw&r=0"
//         },
//         "Airbus A340-500": {
//             "length": 67.90,
//             "capacity": 310,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "2002",
//             "engine_manufacturer": "Rolls-Royce",
//             "engine_name": "Trent 553-61",
//             "models_built": 32,
//             "topspeed": 915,
//             "number_engines": 4,
//             "wingspan": 63.45,
//             "width": 5.64,
//             "flight_range": 16699,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "2002",
//             "type": "Ultra-long range",
//             "airline_companies_used": ["Emirates", "Etihad Airways"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://th.bing.com/th/id/R.21574261532fdd23a6084e351f7963c1?rik=NZsK3HyGpnZeGw&riu=http%3a%2f%2fwww.diecastaircraftforum.com%2fattachment.php%3fattachmentid%3d97537%26stc%3d1%26d%3d1416251002&ehk=65gqBS%2bhymQfgG8z%2f7o8h%2b2FQu6FAX6Wi%2fi3p8RImGQ%3d&risl=&pid=ImgRaw&r=0"
//         },
//         "Airbus A340-600": {
//             "length": 75.36,
//             "capacity": 370,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "2002",
//             "engine_manufacturer": "Rolls-Royce",
//             "engine_name": "Trent 556-61",
//             "models_built": 97,
//             "topspeed": 915,
//             "number_engines": 4,
//             "wingspan": 63.45,
//             "width": 5.64,
//             "flight_range": 14450,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "2001",
//             "type": "Long range",
//             "airline_companies_used": ["Lufthansa", "Virgin Atlantic", "Iberia", "South African Airways"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://th.bing.com/th/id/R.8cc94fe7120b9a7d47c3cb0ba471aab0?rik=WfLA9pPS%2bz3vdw&pid=ImgRaw&r=0"
//         },
//         "Airbus A350-900": {
//             "length": 66.8,
//             "capacity": 350,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "2015",
//             "engine_manufacturer": "Rolls-Royce",
//             "engine_name": "Rolls-Royce Trent XWB",
//             "models_built": 602,
//             "topspeed": 945,
//             "number_engines": 2,
//             "wingspan": 64.75,
//             "width": 5.96,
//             "flight_range": 15000,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "2013",
//             "type": "Long range",
//             "airline_companies_used": ["Singapore Airlines", "Qatar Airways", "Cathay Pacific", "Delta Air Lines"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://th.bing.com/th/id/R.a0992b9438a4824cab2c78d231174cc7?rik=jKokzsXdVU%2fjyQ&pid=ImgRaw&r=0"
//         },
//         "Airbus A350-1000": {
//             "length": 73.79,
//             "capacity": 410,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "2018",
//             "engine_manufacturer": "Rolls-Royce",
//             "engine_name": "Rolls-Royce Trent XWB",
//             "models_built": 602,
//             "topspeed": 945,
//             "number_engines": 2,
//             "wingspan": 64.75,
//             "width": 5.96,
//             "flight_range": 16100,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "2017",
//             "type": "Long range",
//             "airline_companies_used": ["Singapore Airlines", "Qatar Airways", "Cathay Pacific", "Delta Air Lines"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://th.bing.com/th/id/R.68d5896e603ebae041f7a9410df8729c?rik=%2bPwYjQlaUPLIbA&pid=ImgRaw&r=0"
//         },
//         "Airbus A350 XWB": {
//             "length": 73.78,
//             "capacity": 410,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "2015",
//             "engine_manufacturer": "Rolls-Royce",
//             "engine_name": "Rolls-Royce Trent XWB",
//             "models_built": 602,
//             "topspeed": 945,
//             "number_engines": 2,
//             "wingspan": 64.8,
//             "width": 5.96,
//             "flight_range": 15000,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "2013",
//             "type": "Long range",
//             "airline_companies_used": ["Singapore Airlines", "Qatar Airways", "Cathay Pacific", "Delta Air Lines"],
//             "highest_altitude": 41000,
//             "aircraft_image": "https://th.bing.com/th/id/R.0f3588e3180045e655634029165835c5?rik=pFeq8RFvXR8aFg&riu=http%3a%2f%2fwww.gannett-cdn.com%2f-mm-%2f2b7a710613d5b42a57ab7cf6aa632097ada1d055%2fc%3d0-238-3626-2287%26r%3dx1683%26c%3d3200x1680%2flocal%2f-%2fmedia%2f2015%2f07%2f16%2fWIGroup%2fOshkosh%2f635726467472765926-EAAAirbus15-02.jpg&ehk=vY7kbk08pJVcefK%2b1No540IHVL8bmz3OX4PL32LN5tQ%3d&risl=&pid=ImgRaw&r=0"
//         },
//         "Airbus A380-800": {
//             "length": 72.72,
//             "capacity": 853,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 2,
//             "YOEIS": "2007",
//             "engine_manufacturer": "Engine Alliance, Rolls-Royce",
//             "engine_name": "GP7200, Trent 900",
//             "models_built": 254,
//             "topspeed": 1020,
//             "number_engines": 4,
//             "wingspan": 79.75,
//             "width": 7.14,
//             "flight_range": 15200,
//             "aircraft_image": "https://th.bing.com/th/id/R.331170f9cb0d3a5755964a52f20b353b?rik=%2fjSIy1dmirhloQ&pid=ImgRaw&r=0"
//         },
//         "Airbus A380F": {
//             "length": 72.72,
//             "capacity": 150,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 3,
//             "YOEIS": "N/A",
//             "engine_manufacturer": "Engine Alliance, Rolls-Royce",
//             "engine_name": "GP7200, Trent 900",
//             "models_built": 0,
//             "topspeed": 1020,
//             "number_engines": 4,
//             "wingspan": 79.75,
//             "width": 7.14,
//             "flight_range": 10400,
//             "aircraft_image": "https://th.bing.com/th/id/R.7acfdb77338d66197f4018c197b22460?rik=JUZK62QiU7panQ&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2f0%2f09%2fA6-EDY_A380_Emirates_31_jan_2013_jfk_(8442269364)_(cropped).jpg&ehk=y9zRc9loa4fTI%2ffjF2%2b5YxfiZhAcyJrAZseGJhZmHEs%3d&risl=&pid=ImgRaw&r=0"
//         },
//         "Airbus Beluga": {
//             "engine_manufacturer": "General Electric",
//             "engine_name": "General Electric CF6",
//             "models_built": 5,
//             "topspeed": 865,
//             "number_engines": 2,
//             "wingspan": 44.84,
//             "width": 7.1,
//             "length": 56.16,
//             "capacity": 0,
//             "cockpit_crew": 2,
//             "body_type": "wide-body",
//             "num_decks": 1,
//             "YOEIS": "1995",
//             "flight_range": 2770,
//             "engine_type": "High-bypass turbofan",
//             "first_flight": "1994",
//             "type": "Outsize cargo freight aircraft",
//             "airline_companies_used": ["Airbus Transport International"],
//             "highest_altitude": 35000,
//             "aircraft_image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Airbus_Beluga.jpg/800px-Airbus_Beluga.jpg"
//         },
     
        
//             "Boeing 247": {
//                 "engine_manufacturer": "Pratt & Whitney",
//                 "engine_name": "Wasp",
//                 "models_built": 75,
//                 "length": 15.72,
//                 "capacity": 10,
//                 "cockpit_crew": 3,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1933",
//                 "topspeed": 322,
//                 "number_engines": 2,
//                 "wingspan": 22.56,
//                 "width": 3.05,
//                 "flight_range": 1200,
//                 "engine_type": "Radial engine",
//                 "first_flight": "1933",
//                 "type": "Short range",
//                 "airline_companies_used": ["United Airlines"],
//                 "highest_altitude": 25000,
//                 "aircraft_image": "https://static1.simpleflyingimages.com/wordpress/wp-content/uploads/2021/09/Boeing_247-1000x760.jpg"
//             },
//             "Boeing 307 Stratoliner": {
//                 "length": 22.66,
//                 "capacity": 33,
//                 "cockpit_crew": 3,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1940",
//                 "engine_manufacturer": "Wright",
//                 "engine_name": "Cyclone 9",
//                 "models_built": 10,
//                 "topspeed": 396,
//                 "number_engines": 4,
//                 "wingspan": 32.7,
//                 "width": 3.35,
//                 "flight_range": 2400,
//                 "engine_type": "Radial engine",
//                 "first_flight": "1938",
//                 "type": "Long range",
//                 "airline_companies_used": ["Pan American Airways", "TWA"],
//                 "highest_altitude": 23000,
//                 "aircraft_image": "https://th.bing.com/th/id/R.7cdaacdb127d2b6985efb37793179e88?rik=ZUWb9eK8xuk8YQ&pid=ImgRaw&r=0"
//             },
//             "Boeing 707": {
//                 "engine_manufacturer": "Pratt & Whitney",
//                 "engine_name": "JT3D-3B",
//                 "models_built": 865,
//                 "topspeed": 1004,
//                 "number_engines": 4,
//                 "length": 46.61,
//                 "capacity": 189,
//                 "cockpit_crew": 3,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1958",
//                 "wingspan": 44.42,
//                 "width": 3.76,
//                 "flight_range": 7255,
//                 "engine_type": "Turbojet",
//                 "first_flight": "1957",
//                 "type": "Long range",
//                 "airline_companies_used": ["Pan American World Airways", "Trans World Airlines"],
//                 "highest_altitude": 36000,
//                 "aircraft_image": "https://th.bing.com/th/id/R.dd9d1bba82a0cc491346ca5ace094111?rik=HyiQNhUnFCGQJg&pid=ImgRaw&r=0"
//             },
//             "Boeing 707-100B": {
//                 "length": 44.22,
//                 "capacity": 189,
//                 "cockpit_crew": 3,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1958",
//                 "engine_manufacturer": "Pratt & Whitney",
//                 "engine_name": "JT3D",
//                 "models_built": 856,
//                 "topspeed": 1002,
//                 "number_engines": 4,
//                 "wingspan": 39.9,
//                 "width": 3.76,
//                 "flight_range": 7200,
//                 "engine_type": "Low-bypass turbofan",
//                 "first_flight": "1957",
//                 "type": "Long range",
//                 "airline_companies_used": ["Pan American World Airways", "TWA", "American Airlines", "United Airlines"],
//                 "highest_altitude": 42000,
//                 "aircraft_image": "https://www.aviationphotocompany.com/img/s/v-10/p1404988192-3.jpg"
//             },
//             "Boeing 717": {
//                 "engine_manufacturer": "Rolls-Royce Deutschland",
//                 "engine_name": "BR700-715C1-30",
//                 "models_built": 156,
//                 "topspeed": 811,
//                 "number_engines": 2,
//                 "wingspan": 28.45,
//                 "width": 3.14,
//                 "length": 37.81,
//                 "capacity": 134,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1999",
//                 "flight_range": 2645,
//                 "engine_type": "Turbofan",
//                 "first_flight": "1998",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["Southwest Airlines", "Hawaiian Airlines"],
//                 "highest_altitude": 37000,
//                 "aircraft_image": "https://cdn.airlines-inform.ru/upload/iblock/fa3/Boeing-717.JPG"
//             },
//             "Boeing 727": {
//                 "engine_manufacturer": "Pratt & Whitney",
//                 "engine_name": "JT8D-7",
//                 "models_built": 1832,
//                 "topspeed": 943,
//                 "number_engines": 3,
//                 "wingspan": 32.92,
//                 "width": 3.8,
//                 "length": 46.68,
//                 "capacity": 189,
//                 "cockpit_crew": 3,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1964",
//                 "flight_range": 2700,
//                 "engine_type": "Low-bypass turbofan",
//                 "first_flight": "1963",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["United Airlines", "American Airlines"],
//                 "highest_altitude": 42000,
//                 "aircraft_image": "https://th.bing.com/th/id/R.d26e5307909caefcd637ec721dd30a86?rik=gZYka59gFxvnPA&pid=ImgRaw&r=0"
//             },
//             "Boeing 737-100": {
//                 "engine_manufacturer": "Pratt & Whitney",
//                 "engine_name": "JT8D-7",
//                 "models_built": 30,
//                 "topspeed": 943,
//                 "number_engines": 2,
//                 "wingspan": 28.35,
//                 "width": 3.76,
               
//                     "length": 28.65,
//                     "capacity": 85,
//                     "cockpit_crew": 2,
//                     "body_type": "narrow-body",
//                     "num_decks": 1,
//                     "YOEIS": "1968",
//                 "flight_range": 2855,
//                 "engine_type": "Low-bypass turbofan",
//                 "first_flight": "1967",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["Lufthansa"],
//                 "highest_altitude": 35000,
//                 "aircraft_image": "https://aerocorner.com/wp-content/uploads/2020/02/Lufthansa-Boeing-737-100-Takeoff-1090x500.jpg"
//             },
//             "Boeing 737-200": {
//                 "engine_manufacturer": "Pratt & Whitney",
//                 "engine_name": "JT8D-9A",
//                 "models_built": 1095,
//                 "topspeed": 943,
//                 "number_engines": 2,
//                 "wingspan": 28.35,
//                 "width": 3.76,
//                 "length": 30.53,
//                 "capacity": 115,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1968",
//                 "flight_range": 4260,
//                 "engine_type": "Low-bypass turbofan",
//                 "first_flight": "1967",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["United Airlines"],
//                 "highest_altitude": 35000,
//                 "aircraft_image": "https://th.bing.com/th/id/OIP.kKn5rr8dSnZusI6hbxvRHwHaE8?rs=1&pid=ImgDetMain"
//             },
//             "Boeing 737-300": {
//                 "engine_manufacturer": "CFM International",
//                 "engine_name": "CFM56-3B2",
//                 "models_built": 1113,
//                 "topspeed": 946,
//                 "number_engines": 2,
//                 "wingspan": 28.88,
//                 "width": 3.76,
//                 "length": 33.40,
//                 "capacity": 149,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1984",
//                 "flight_range": 5463,
//                 "engine_type": "High-bypass turbofan",
//                 "first_flight": "1984",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["Southwest Airlines"],
//                 "highest_altitude": 37000,
//                 "aircraft_image": "https://th.bing.com/th/id/R.636f8a33ab2dc2a0333437a14ffc0be9?rik=ePNTns1AxKVqUg&pid=ImgRaw&r=0"
//             },
//             "Boeing 737-400": {
//                 "engine_manufacturer": "CFM International",
//                 "engine_name": "CFM56-3C1",
//                 "models_built": 486,
//                 "topspeed": 943,
//                 "number_engines": 2,
//                 "wingspan": 28.88,
//                 "width": 3.76,
//                 "length": 36.45,
//                 "capacity": 168,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1988",
//                 "flight_range": 4260,
//                 "engine_type": "High-bypass turbofan",
//                 "first_flight": "1988",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["Piedmont Airlines"],
//                 "highest_altitude": 37000,
//                 "aircraft_image": "https://th.bing.com/th/id/R.9c6f6ff44179cc7386b44b188155e9d8?rik=Cm7UGTANypgzrQ&pid=ImgRaw&r=0"
//             },
//             "Boeing 737-500": {
//                 "engine_manufacturer": "CFM International",
//                 "engine_name": "CFM56-3B1",
//                 "models_built": 389,
//                 "topspeed": 946,
//                 "number_engines": 2,
//                 "wingspan": 28.88,
//                 "width": 3.76,
//                 "length": 31.01,
//                 "capacity": 132,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1990",
//                 "flight_range": 5463,
//                 "engine_type": "High-bypass turbofan",
//                 "first_flight": "1989",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["Southwest Airlines"],
//                 "highest_altitude": 37000,
//                 "aircraft_image": "https://th.bing.com/th/id/R.30e8a059c3a8d85112ff6aeee0a1a37a?rik=VT9SQSUvznsnJA&riu=http%3a%2f%2fbarrieaircraft.com%2fimages%2fboeing-737-500-03.jpg&ehk=iHg9AZHzb%2fxKJUbnbLQpg9bLGSMjJ%2fuvBDRhyHD0gxg%3d&risl=&pid=ImgRaw&r=0"
//             },
//             "Boeing 737-600": {
//                 "engine_manufacturer": "CFM International",
//                 "engine_name": "CFM56-7B22",
//                 "models_built": 69,
//                 "topspeed": 943,
//                 "number_engines": 2,
//                 "wingspan": 34.31,
//                 "width": 3.76,
//                 "length": 31.24,
//                 "capacity": 132,
//                 "cockpit_crew": 2,
//                 "body_type": "narrow-body",
//                 "num_decks": 1,
//                 "YOEIS": "1998",
//                 "flight_range": 5463,
//                 "engine_type": "High-bypass turbofan",
//                 "first_flight": "1998",
//                 "type": "Short to medium range",
//                 "airline_companies_used": ["Scandinavian Airlines"],
//                 "highest_altitude": 41000,
//                 "aircraft_image": "https://cdn.airlines-inform.ru/upload/iblock/c63/Boeing-737-600.JPG"
//             },
            
//               "Boeing 737-700": {
//                     "engine_manufacturer": "CFM International",
//                     "engine_name": "CFM56-7B24",
//                     "models_built": 1124,
//                     "topspeed": 946,
//                     "number_engines": 2,
//                     "wingspan": 34.32,
//                     "width": 3.76,
//                     "length": 33.63,
//                     "capacity": 149,
//                     "cockpit_crew": 2,
//                     "body_type": "narrow-body",
//                     "num_decks": 1,
//                     "YOEIS": "1997",
//                     "flight_range": 6482,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "1997",
//                     "type": "Short to medium range",
//                     "airline_companies_used": ["Southwest Airlines", "United Airlines"],
//                     "highest_altitude": 41000,
//                     "aircraft_image": "https://th.bing.com/th/id/R.224643d7acde5bb72696b1e2b25ed962?rik=2JoN3GsEBWP23A&riu=http%3a%2f%2fairplanes.itsabouttravelling.com%2fwp-content%2fuploads%2f2017%2f12%2fc-fbwj-westjet-boeing-737-700-02.jpg&ehk=2Wpmg5qkoEqTLY4qfHB7p6oPSVSD%2bUdAx1LjGrxwYlM%3d&risl=1&pid=ImgRaw&r=0"
//             },
//                 "Boeing 737-800": {
//                     "engine_manufacturer": "CFM International",
//                     "engine_name": "CFM56-7B27",
//                     "models_built": 4991,
//                     "topspeed": 946,
//                     "number_engines": 2,
//                     "wingspan": 34.32,
//                     "width": 3.76,
//                     "length": 39.47,
//                     "capacity": 189,
//                     "cockpit_crew": 2,
//                     "body_type": "narrow-body",
//                     "num_decks": 1,
//                     "YOEIS": "1998",
//                     "flight_range": 5463,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "1997",
//                     "type": "Short to medium range",
//                     "airline_companies_used": ["Ryanair", "American Airlines"],
//                     "highest_altitude": 41000,
//                     "aircraft_image": "https://th.bing.com/th/id/OIP.tTSMQcR3iqwRsZD6_yKPwwHaE8?rs=1&pid=ImgDetMain"
//                 },
//                 "Boeing 737-900": {
//                     "engine_manufacturer": "CFM International",
//                     "engine_name": "CFM56-7B27",
//                     "models_built": 52,
//                     "topspeed": 946,
//                     "number_engines": 2,
//                     "wingspan": 34.32,
//                     "width": 3.76,
//                     "length": 42.11,
//                     "capacity": 220,
//                     "cockpit_crew": 2,
//                     "body_type": "narrow-body",
//                     "num_decks": 1,
//                     "YOEIS": "2000",
//                     "flight_range": 5463,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "2000",
//                     "type": "Short to medium range",
//                     "airline_companies_used": ["Alaska Airlines", "United Airlines"],
//                     "highest_altitude": 41000,
//                     "aircraft_image": "https://th.bing.com/th/id/R.1bfa85615d8c12f2429884b7f10af661?rik=rXylxqHY389D2w&riu=http%3a%2f%2ftheflight.info%2fwp-content%2fgallery%2fUnited-Airlines-Boeing-737-900%2fn37419-united-airlines-boeing-737-924erwl.jpg&ehk=tPKHAQJ2iOdTzhQEkQ7kOBAuQSQmFfcdGhx%2fUfANA%2b0%3d&risl=&pid=ImgRaw&r=0"
//                 },
//                 "Boeing 737 MAX": {
//                     "engine_manufacturer": "CFM International",
//                     "engine_name": "LEAP-1B",
//                     "models_built": 450,
//                     "topspeed": 839,
//                     "number_engines": 2,
//                     "wingspan": 35.92,
//                     "width": 3.54,
//                     "length": 43.8,
//                     "capacity": 230,
//                     "cockpit_crew": 2,
//                     "body_type": "narrow-body",
//                     "num_decks": 1,
//                     "YOEIS": "2017",
//                     "flight_range": 6570,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "2016",
//                     "type": "Short to medium range",
//                     "airline_companies_used": ["Southwest Airlines", "Air Canada"],
//                     "highest_altitude": 41000,
//                     "aircraft_image": "https://andystravelblog.com/wp-content/uploads/2019/03/K65946-2048x1638.jpg"
//                 },
//                 "Boeing 747-100": {
//                     "engine_manufacturer": "Pratt & Whitney",
//                     "engine_name": "JT9D-7A",
//                     "models_built": 167,
//                     "topspeed": 988,
//                     "number_engines": 4,
//                     "wingspan": 59.64,
//                     "width": 6.1,
//                     "length": 70.66,
//                     "capacity": 480,
//                     "cockpit_crew": 3,
//                     "body_type": "wide-body",
//                     "num_decks": 2,
//                     "YOEIS": "1970",
//                     "flight_range": 9200,
//                     "engine_type": "Low-bypass turbofan",
//                     "first_flight": "1969",
//                     "type": "Long range",
//                     "airline_companies_used": ["Pan American World Airways"],
//                     "highest_altitude": 45000,
//                     "aircraft_image": "https://th.bing.com/th/id/R.3980db26a0c23b1246a4e3782a758596?rik=plR9YDdLhqE7NA&riu=http%3a%2f%2fwww.airlinereporter.com%2fwp-content%2fuploads%2f2015%2f10%2f9625269779_7d51118a9f_k.jpg&ehk=3xEa%2b9MEXD6jQLMgWdg66oBG3V%2bi9bRiDeAABcCfqXo%3d&risl=&pid=ImgRaw&r=0"
//                 },
//                 "Boeing 747-200": {
//                     "engine_manufacturer": "Pratt & Whitney",
//                     "engine_name": "JT9D-7Q",
//                     "models_built": 393,
//                     "topspeed": 988,
//                     "number_engines": 4,
//                     "wingspan": 59.64,
//                     "width": 6.1,
//                     "length": 70.66,
//                     "capacity": 480,
//                     "cockpit_crew": 3,
//                     "body_type": "wide-body",
//                     "num_decks": 2,
//                     "YOEIS": "1971",
//                     "flight_range": 12200,
//                     "engine_type": "Low-bypass turbofan",
//                     "first_flight": "1971",
//                     "type": "Long range",
//                     "airline_companies_used": ["British Airways"],
//                     "highest_altitude": 45000,
//                     "aircraft_image": "https://th.bing.com/th/id/R.1ae323fbd3bfed4ded9010759ca94ac3?rik=m1j4AztiuCe8fA&pid=ImgRaw&r=0"
//                 },
//                 "Boeing 747-400": {
//                     "engine_manufacturer": "General Electric",
//                     "engine_name": "CF6-80C2B1F",
//                     "models_built": 694,
//                     "topspeed": 988,
//                     "number_engines": 4,
//                     "wingspan": 64.44,
//                     "width": 6.1,
//                     "length": 70.66,
//                     "capacity": 660,
//                     "cockpit_crew": 2,
//                     "body_type": "wide-body",
//                     "num_decks": 2,
//                     "YOEIS": "1989",
//                     "flight_range": 13430,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "1988",
//                     "type": "Long range",
//                     "airline_companies_used": ["British Airways", "Lufthansa"],
//                     "highest_altitude": 45000,
//                     "aircraft_image": "https://th.bing.com/th/id/R.5a2b8f364ebb864757a0252b5e4b618c?rik=znjj99j7AnNLWg&riu=http%3a%2f%2faustralianaviation.com.au%2fwp-content%2fuploads%2f2019%2f02%2fBoeing_747_KLM_PH-BFB.jpg&ehk=1k0RCoCtYgsQJrVDdNa%2b5gwbBlU0GyA4k08LFoIfZG0%3d&risl=&pid=ImgRaw&r=0"
//                 },
//                 "Boeing 747-8": {
//                     "engine_manufacturer": "General Electric",
//                     "engine_name": "GEnx-2B67",
//                     "models_built": 155,
//                     "topspeed": 988,
//                     "number_engines": 4,
//                     "wingspan": 68.45,
//                     "width": 6.1,
//                     "length": 76.25,
//                     "capacity": 700,
//                     "cockpit_crew": 2,
//                     "body_type": "wide-body",
//                     "num_decks": 2,
//                     "YOEIS": "2012",
//                     "flight_range": 14815,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "2010",
//                     "type": "Long range",
//                     "airline_companies_used": ["Lufthansa", "Korean Air"],
//                     "highest_altitude": 43000,
//                     "aircraft_image": "https://th.bing.com/th/id/R.e45f00839b7cd971d02484434ee4ed76?rik=K%2bcGjKk4GP%2fxyw&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2f8%2f88%2fLufthansa_Boeing_747-8_(16278574162).jpg&ehk=R3QT5e8TF2TV8temfRXpsg3e5yE6OIyYaSPV4Tih3fc%3d&risl=1&pid=ImgRaw&r=0"
//                 },
//                 "Boeing 757": {
//                     "engine_manufacturer": "Rolls-Royce",
//                     "engine_name": "RB211-535E4",
//                     "models_built": 1050,
//                     "topspeed": 982,
//                     "number_engines": 2,
//                     "wingspan": 38.05,
//                     "width": 3.54,
//                     "length": 47.32,
//                     "capacity": 239,
//                     "cockpit_crew": 2,
//                     "body_type": "narrow-body",
//                     "num_decks": 1,
//                     "YOEIS": "1983",
//                     "flight_range": 7222,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "1982",
//                     "type": "Short to medium range",
//                     "airline_companies_used": ["Delta Air Lines", "United Airlines"],
//                     "highest_altitude": 42000,
//                     "aircraft_image": "https://th.bing.com/th/id/OIP.mm-Fu7iywR7IFdiB3YJeKwHaE8?rs=1&pid=ImgDetMain"
//                 },
//                 "Boeing 767-200": {
//                     "engine_manufacturer": "General Electric",
//                     "engine_name": "CF6-80A",
//                     "models_built": 128,
//                     "topspeed": 851,
//                     "number_engines": 2,
//                     "wingspan": 47.57,
//                     "width": 4.72,
//                     "length": 48.51,
//                     "capacity": 255,
//                     "cockpit_crew": 2,
//                     "body_type": "wide-body",
//                     "num_decks": 1,
//                     "YOEIS": "1982",
//                     "flight_range": 7222,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "1981",
//                     "type": "Medium to long range",
//                     "airline_companies_used": ["Delta Air Lines", "United Airlines"],
//                     "highest_altitude": 43000,
//                     "aircraft_image": "https://th.bing.com/th/id/R.c2a7d7323d468e73a330e14bacee641a?rik=gtxG4NIZC5PTaQ&pid=ImgRaw&r=0"
//                 },
//                 "Boeing 767-300": {
//                     "engine_manufacturer": "General Electric",
//                     "engine_name": "CF6-80C2B2F",
//                     "models_built": 1040,
//                     "topspeed": 850,
//                     "number_engines": 2,
//                     "wingspan": 47.57,
//                     "width": 4.72,
//                     "length": 54.94,
//                     "capacity": 269,
//                     "cockpit_crew": 2,
//                     "body_type": "wide-body",
//                     "num_decks": 1,
//                     "YOEIS": "1986",
//                     "flight_range": 11107,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "1986",
//                     "type": "Medium to long range",
//                     "airline_companies_used": ["Delta Air Lines", "FedEx Express", "UPS Airlines", "United Airlines"],
//                     "highest_altitude": 43100,
//                     "aircraft_image": "https://th.bing.com/th/id/R.387a92885711e6ed261847be570a2d58?rik=pxK6ofE4KY1uoA&riu=http%3a%2f%2fupload.wikimedia.org%2fwikipedia%2fcommons%2f3%2f3f%2fDelta_Airline_Boeing_767-300_N180DN.jpg&ehk=oDvmDxgJkWWna5WLgXd%2fbTaYQ8I3bA9AE2sqE%2bDeI0M%3d&risl=&pid=ImgRaw&r=0"
//                 },
//                 "Boeing 767-400ER": {
//                     "engine_manufacturer": "Pratt & Whitney",
//                     "engine_name": "PW4060",
//                     "models_built": 37,
//                     "topspeed": 850,
//                     "number_engines": 2,
//                     "wingspan": 51.9,
//                     "width": 4.72,
//                     "length": 61.37,
//                     "capacity": 296,
//                     "cockpit_crew": 2,
//                     "body_type": "wide-body",
//                     "num_decks": 1,
//                     "YOEIS": "2000",
//                     "flight_range": 10415,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "2000",
//                     "type": "Medium to long range",
//                     "airline_companies_used": ["United Airlines", "Delta Air Lines"],
//                     "highest_altitude": 43100,
//                     "aircraft_image": "https://th.bing.com/th/id/R.9efcfdb05ee81d1e773439a395436a5b?rik=LshBgWnUgs%2f6Xw&pid=ImgRaw&r=0"
//                 },
//                 "Boeing 787-8": {
//                     "engine_manufacturer": "General Electric",
//                     "engine_name": "GEnx-1B64",
//                     "models_built": 397,
//                     "topspeed": 954,
//                     "number_engines": 2,
//                     "wingspan": 60.12,
//                     "width": 5.49,
//                     "length": 56.72,
//                     "capacity": 242,
//                     "cockpit_crew": 2,
//                     "body_type": "wide-body",
//                     "num_decks": 1,
//                     "YOEIS": "2011",
//                     "flight_range": 13804,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "2011",
//                     "type": "Long range",
//                     "airline_companies_used": ["All Nippon Airways", "United Airlines", "American Airlines", "Qatar Airways", "Japan Airlines", "Etihad Airways", "Hainan Airlines", "Air Canada", "British Airways", "Ethiopian Airlines", "Air India"],
//                     "highest_altitude": 43100,
//                     "aircraft_image": "https://th.bing.com/th/id/R.ab40a11029d309fd14da298a537e7821?rik=NsRmA09AnyvNSA&riu=http%3a%2f%2fbarrieaircraft.com%2fimages%2fboeing-787-8-dreamliner-01.jpg&ehk=loAu8dlPp5XQCNqLZ%2f7B01xVRflOGmiAUMmoD9v0ISM%3d&risl=&pid=ImgRaw&r=0"
//                 },
//                 "Boeing 787-9": {
//                     "engine_manufacturer": "General Electric",
//                     "engine_name": "GEnx-1B74",
//                     "models_built": 621,
//                     "topspeed": 954,
//                     "number_engines": 2,
//                     "wingspan": 60.12,
//                     "width": 5.49,
//                     "length": 62.81,
//                     "capacity": 290,
//                     "cockpit_crew": 2,
//                     "body_type": "wide-body",
//                     "num_decks": 1,
//                     "YOEIS": "2014",
//                     "flight_range": 14140,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "2013",
//                     "type": "Long range",
//                     "airline_companies_used": ["All Nippon Airways", "United Airlines", "American Airlines", "Qatar Airways", "Japan Airlines", "Etihad Airways", "Hainan Airlines", "Air Canada", "British Airways", "Ethiopian Airlines", "Air India"],
//                     "highest_altitude": 43100,
//                     "aircraft_image": "https://th.bing.com/th/id/R.1f309e8f7c0ff1ef67bb718064bf5a2b?rik=3yGr%2fZjYuFhLkQ&riu=http%3a%2f%2fwww.gannett-cdn.com%2f-mm-%2f0c3311e750009feb3aaf9542f948a35b17b5c5d6%2fc%3d373-311-5049-2957%26r%3dx1683%26c%3d3200x1680%2flocal%2f-%2fmedia%2fUSATODAY%2fUSATODAY%2f2013%2f09%2f18%2f1379515730000-AP-Boeing-787-9.jpg&ehk=gu6s6YPDfYm8rwG%2fmOsIHHQJ8i88cP9SFJuhnDgq4DU%3d&risl=&pid=ImgRaw&r=0"
//                 },
//                 "Boeing 787-10": {
//                     "engine_manufacturer": "General Electric",
//                     "engine_name": "GEnx-1B76",
//                     "models_built": 97,
//                     "topspeed": 954,
//                     "number_engines": 2,
//                     "wingspan": 60.12,
//                     "width": 5.49,
//                     "length": 68.28,
//                     "capacity": 330,
//                     "cockpit_crew": 2,
//                     "body_type": "wide-body",
//                     "num_decks": 1,
//                     "YOEIS": "2017",
//                     "flight_range": 11730,
//                     "engine_type": "High-bypass turbofan",
//                     "first_flight": "2017",
//                     "type": "Long range",
//                     "airline_companies_used": ["Singapore Airlines", "Etihad Airways", "United Airlines"],
//                     "highest_altitude": 43100,
//                     "aircraft_image": "https://th.bing.com/th/id/OIP.JLpEnL1rh66RQJzg9MdPTAHaE_?rs=1&pid=ImgDetMain"
//                 }
//             }
//         }